import type {Metadata} from "next";
import {Inter} from "next/font/google";
// import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export async function generateStaticParams() {
    return [{lang: 'en-US'}, {lang: 'de'}]
}

export default function RootLayout({ children, params}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang={params.lang}>
        <body>{children}</body>
        </html>
    );
}
