import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import {NextIntlClientProvider} from "next-intl";
import {getMessages} from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props =
{
    children: React.ReactNode;
    params: { locale: string}
}

// export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
export default async function RootLayout({ children, params } : Props) {
    const messages = await getMessages();
    return (
        <html lang={params.locale}>

        <body>
        <NextIntlClientProvider messages={messages}>
        <Header />
        {children}
        {/*<Footer />*/}
        </NextIntlClientProvider>
        </body>

        </html>
    );
}